SELECT DISTINCT C1.CNAME,C2.CNAME
FROM COMPANY C1 JOIN COMPANY C2
ON( C1.CNAME <> C2.CNAME)

EXCEPT

(SELECT  DISTINCT C1.CNAME,C2.CNAME 
FROM COMPANY C1 JOIN COMPANY C2
 ON (C1.CNAME <> C2.CNAME) 
 JOIN WORKSFOR WF ON (WF.CNAME = C1.CNAME) 
 NATURAL JOIN PERSON P 
WHERE P.CITY = 'Chicago')
 
EXCEPT

(SELECT  DISTINCT C1.CNAME,C2.CNAME 
FROM COMPANY C1 JOIN COMPANY C2 
  ON (C1.CNAME <> C2.CNAME) 
 JOIN WORKSFOR WF1 ON (WF1.CNAME = C2.CNAME) 
 NATURAL JOIN PERSON P1
WHERE P1.CITY = 'Chicago')

